[features]
seeds = true

[programs.devnet]
staking_program = "3kQFUTjSMZFe1pDCFF9dL7nRAFQrhvKEMHDJDAuGLcZa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"